### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by jlopezsi** [ccbogel/QualCoder-Debians#1]
I have installed version 1.3 on Ubuntu 18.04 and worked fine, but when installing qualcoder 1.4.1 it fails at starting the application.
I've read that only Debian package works with versions 1.4.1, is it true?
I work with Ubuntu, OSX and windows, so I can help testing the version in different platforms.
I appreciate any help.
Thanks

**Comment by ccbogel** [comment]
Thank you for letting me know Jordi. 
If you download the qualcder code: [https://github.com/ccbogel/QualCoder](https://github.com/ccbogel/QualCoder )
After unzipping the download, can you run the program from the terminal: 
e.g. `python3 Downloads/QualCoder-master/qualcoder/qualcoder.py`
The error messages might help me.
with regards Colin

**Comment by jlopezsi** [comment]
Colin,
I've installed the Debian package 1.4.1 and y get the error that you can
see in the screenshot I've taken just when I start the program. Version 1.3
was installed fine, but version 1.4.1 produces several errors.
I'm interested in version 1.4.1 as it offers the possibility of reading a
RQDA project. Current I use RQDA with my master students module of
qualitative analysis, but I'd like to migrate to qualcoder. However I have
some projects already coded with RQDA and it would be nice to be able to
migrate them to qualcoder.
Thanks for your help,
Jordi
*------------------------------------------------------------*

*Jordi López-Sintas, PhD <https://jlopezsi.netlify.com>*
*Catedràtic d'universitat, Comercializació i investigació de mercats (full
professor of marketing and consumer research)**, *Department
d'Empresa, Universitat Autónoma
de Barcelona <http://www.uab.cat>, Spain.

President d'Espacual <https://www.espacual.es>, Asociación Española para el
Avance de la Investigación Cualitativa (2016-2022)

**Comment by ccbogel** [comment]
Hello Jordi,
Where is the screenshot, I cannot see in in your message?
I am going to guess one thing - another code contributor added a module called 'click' which I do not think is necessary, so I will remove that module. 
Glad to know that you are finding QualCoder useful other than this installation issue.
Colin

**Comment by ccbogel** [comment]
Hello Jordi, I have made a newer debian file qualcoder1.5.deb  
I hope this fixes the previous installation and running issues.

**Comment by jlopezsi** [comment]
Colin,
Now we have reduced the number of errors , but still there are a few that
prevent the program to be open. This is in ubuntu 18.04.

Traceback (most recent call last):

File "/usr/share/qualcoder/qualcoder.py", line 1075, in <module>

gui()


File "/usr/share/qualcoder/qualcoder.py", line 1070, in gui

ex.open_project(path=project_path)


File "/usr/share/qualcoder/qualcoder.py", line 991, in open_project

backup = self.settings['path'][0:-4] + "_BACKUP_" + nowdate + ".qda"


AttributeError: 'MainWindow' object has no attribute 'settings'


Thanks
*------------------------------------------------------------*

*Jordi López-Sintas, PhD <https://jlopezsi.netlify.com>*
*Catedràtic d'universitat, Comercializació i investigació de mercats (full
professor of marketing and consumer research)**, *Department
d'Empresa, Universitat Autónoma
de Barcelona <http://www.uab.cat>, Spain.

President d'Espacual <https://www.espacual.es>, Asociación Española para el
Avance de la Investigación Cualitativa (2016-2022)

**Comment by ccbogel** [comment]
Ok thanks for this, try again, I updated the debian.
You might also need to install pdfminer.six:
`sudo pip install pdfminer.six`

**Comment by jlopezsi** [comment]
Colin,
I’ve install the new debian package in Ubuntu 16.04, 18.04 and Mac OSX. In
Ubuntu 16.04 the Debian package works perfectly, in Mac OSX the downloaded
master folder works fine, but in Ubuntu 18.04, the REFI-QDA project import
and the RQDA project import are in gray and can not be activated.
Any idea why?
Thank,
Jordi

*------------------------------------------------------------*

*Jordi López-Sintas, PhD <https://jlopezsi.netlify.com>*
*Catedràtic d'universitat, Comercializació i investigació de mercats (full
professor of marketing and consumer research)**, *Department
d'Empresa, Universitat Autónoma
de Barcelona <http://www.uab.cat>, Spain.

President d'Espacual <https://www.espacual.es>, Asociación Española para el
Avance de la Investigación Cualitativa (2016-2022)

**Comment by ccbogel** [comment]
Jordi, 
Finally! I am glad everything is working again for you.
 
> The REFI-QDA project import and the RQDA project import are in gray and can not be activated.

Yes, this is normal. When you have a project opened, these will be gray and not active. 
Qualcoder will automatically open the last project you worked on, when you open qualcoder.
So to use the imports, go to the File menu and click on Close project. Then you should see these imports are now active.

Also, the REFI-project import is still experimental and does not comply fully with the REFI standards. A main issue I found with Nvivo import was that the text coding start and end positions do not match correctly.

Please let me know if this fixes the issue, and I will close this issue down.

I can try and use Google translate to convert English to Spanish for qualcoder. If you like.

with regards Colin

**Comment by ccbogel** [comment]
It has been nearly one month since the last post. So will close this issue.
