### ISSUE TITLE
Installing Debian-Package required fixing permissions and manual installation of pdfminer.six

### ISSUE THREAD

**Issue by mekeor** [ccbogel/QualCoder-Debians#2]
I though it would be enough to download the latest DEB-package and install it with `sudo dpkg -i qualcoder-1.7.deb`. But the file `/usr/bin/qualcoder` had wrong permissions. Also, I had to install the `pdfminer.six` Python-package, although I thought it was optional.

So, this was my complete installation process (on Debian):

```
sudo apt install python3-pyqt5 python3-lxml qpdf python3-ebooklib  python3-ply python3-pip
sudo python3 -m pip install pdfminer.six
sudo dpkg -i qualcoder-1.7.deb
sudo chmod 755 /usr/bin/qualcoder
```

So my proposals are:

1. The README should say that it is *required* to install `pdfminer.six`
2. The `/usr/bin/qualcoder` executable should have the correct permissions automatically after installation.

Thank you for developing!

**Comment by ccbogel** [comment]
Hopefully fixed in the latest debian 1.8.
I also updated the install instructions.
Let me know how you like qualcoder.
with regards Colin
